#ifndef MACHINES_H
#define MACHINES_H
const char *machines[193] = {"No machine",
			     "AT&T WE 32100",
			     "SUN SPARC",
			     "Intel 80386",
			     "Motorola m68k family",
			     "Motorola m88k family",
			     NULL,
			     "Intel 80860",
			     "MIPS R3000 big-endian",
			     "IBM System/370",
			     "MIPS R3000 little-endian",
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     "HPPA",
			     NULL,
			     "Fujitsu VPP500",
			     "Sun's \" v8plus \"",
			     "Intel 80960",
			     "PowerPC",
			     "PowerPC 64-bit",
			     "IBM S390",
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     "NEC V800 series",
			     "Fujitsu FR20",
			     "TRW RH-32",
			     "Motorola RCE",
			     "ARM",
			     "Digital Alpha",
			     "Hitachi SH",
			     "SPARC v9 64-bit",
			     "Siemens Tricore",
			     "Argonaut RISC Core",
			     "Hitachi H8/300",
			     "Hitachi H8/300H",
			     "Hitachi H8S",
			     "Hitachi H8/500",
			     "Intel Merced",
			     "Stanford MIPS-X",
			     "Motorola Coldfire",
			     "Motorola M68HC12",
			     "Fujitsu MMA Multimedia",
			     "Siemens PCP",
			     "Sony nCPU embeeded RISC",
			     "Denso NDR1 microprocessor",
			     "Motorola Start*Core processor",
			     "Toyota ME16 processor",
			     "STMicroelectronic ST100 processor",
			     "Advanced Logic Corp. Tinyj",
			     "Advanced Micro Devices X86-64",
			     "Sony DSP Processor",
			     NULL,
			     NULL,
			     "Siemens FX66 microcontroller",
			     "STMicroelectronics ST9+ 8/16 mc",
			     "STmicroelectronics ST7 8 bit mc",
			     "Motorola MC68HC16 microcontroller",
			     "Motorola MC68HC11 microcontroller",
			     "Motorola MC68HC08 microcontroller",
			     "Motorola MC68HC05 microcontroller",
			     "Silicon Graphics SVx",
			     "STMicroelectronics ST19 8 bit mc",
			     "Digital VAX",
			     "Axis Communications 32-bit embedded processor",
			     "Infineon Technologies 32-bit embedded processor",
			     "Element 14 64-bit DSP Processor",
			     "LSI Logic 16-bit DSP Processor",
			     "Donald Knuth's educational 64-bit processor",
			     "Harvard University machine-independent object files",
			     "SiTera Prism",
			     "Atmel AVR 8-bit microcontroller",
			     "Fujitsu FR30",
			     "Mitsubishi D10V",
			     "Mitsubishi D30V",
			     "NEC v850",
			     "Mitsubishi M32R",
			     "Matsushita MN10300",
			     "Matsushita MN10200",
			     "picoJava",
			     "OpenRISC 32-bit embedded processor",
			     "ARC Cores Tangent-A5",
			     "Tensilica Xtensa Architecture",
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     "ARM AARCH64",
			     NULL,
			     NULL,
			     NULL,
			     NULL,
			     "Tilera TILEPro",
			     "Xilinx MicroBlaze",
			     NULL,
			     "Tilera TILE-Gx",
			     NULL};
#endif /* MACHINES_H */
